"use client";

import {useEffect,useState} from 'react';
import {ArrowUpRight,ArrowRight,ScanLine,Radio,Eye,Brain,Activity,Waves,Menu,X,ChevronDown,Shield,Database,Network,Zap} from 'lucide-react';

const moods=[{name:'CURIOUS',line:'Something’s moving. Let me look closer.',color:'#bb92ff'},{name:'SUSPICIOUS',line:'That wallet has been a little too quiet.',color:'#ffbb71'},{name:'LOCKED IN',line:'Less noise. More on-chain receipts.',color:'#86e3c6'}];
const modules=[{name:'Clank Radar',tag:'DISCOVER',icon:Radio,text:'Fresh launches. Unusual momentum. The next thing worth a closer look.',detail:'Watch new pairs, liquidity changes, token age, and volume acceleration in one stream.'},{name:'Booty Metrics',tag:'UNDERSTAND',icon:Activity,text:'Big energy. Actual numbers. A clearer picture of what’s happening on-chain.',detail:'Liquidity depth, holder concentration, trading activity, and deployer behavior. Metrics, never an investment rating.'},{name:'Wallet Stalker',tag:'FOLLOW',icon:Eye,text:'Some wallets speak louder than timelines. Follow the receipts.',detail:'Explore public wallet activity and recurring behavior. No wallet connection or private keys required.'},{name:'BBC Memory',tag:'REMEMBER',icon:Brain,text:'She remembers the pattern. Even when the timeline forgets.',detail:'Your demo scans stay in this browser. A future intelligence layer will connect changes across time.'},{name:'Whale Watch',tag:'DETECT',icon:Waves,text:'Big moves make waves. Know where the ripples started.',detail:'Surface large transfers, accumulation patterns, and liquidity movements with their transaction context.'}];
const sample='0x7A3e91B420Fa25c602c856eEe925bA2137bEd091';
const terminalLines=['> initializing behavioral core…','✓ personality loaded: playfully analytical','✓ scanner + radar modules staged','✓ whale observation deck ready','> connecting curiosity to the chain…','BBC IS LAUNCHING SOON_'];
export default function Home(){
 const [menu,setMenu]=useState(false),[mood,setMood]=useState(0),[address,setAddress]=useState(''),[error,setError]=useState(''),[scanning,setScanning]=useState(false),[result,setResult]=useState(false),[expanded,setExpanded]=useState<number|null>(null),[history,setHistory]=useState<string[]>([]),[lines,setLines]=useState(0);
 useEffect(()=>{try{setHistory(JSON.parse(localStorage.getItem('bbc-scans')||'[]'))}catch{} const timer=setInterval(()=>setMood(m=>(m+1)%moods.length),6500); const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');if(e.target.id==='terminal')setLines(1)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));return()=>{clearInterval(timer);observer.disconnect()}},[]);
 useEffect(()=>{if(lines>0&&lines<terminalLines.length){const t=setTimeout(()=>setLines(l=>l+1),700);return()=>clearTimeout(t)}},[lines]);
 useEffect(()=>{if(!scanning)return;const t=setTimeout(()=>{setScanning(false);setResult(true);setHistory(old=>{const next=[address,...old.filter(a=>a!==address)].slice(0,4);try{localStorage.setItem('bbc-scans',JSON.stringify(next))}catch{}return next})},1600);return()=>clearTimeout(t)},[scanning,address]);
 function scan(){setError('');setResult(false);if(!/^0x[a-fA-F0-9]{40}$/.test(address.trim())){setError('Enter a valid EVM contract address (0x + 40 hexadecimal characters).');return}setAddress(address.trim());setScanning(true)}
 return <main>
 <header className="header"><a className="brand" href="#" aria-label="BBC home"><span className="brand-symbol">b.</span>BBC<span className="brand-sub">BEHAVIORAL BLOCKCHAIN<br/>COMPANION</span></a><nav className={menu?'nav open':'nav'} aria-label="Main navigation"><a href="#intelligence" onClick={()=>setMenu(false)}>Intelligence</a><a href="#scanner" onClick={()=>setMenu(false)}>Scanner</a><a href="#architecture" onClick={()=>setMenu(false)}>Architecture</a></nav><a className="header-cta" href="#terminal">Launching soon <ArrowUpRight size={16}/></a><button className="menu" aria-label={menu?'Close navigation':'Open navigation'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
 <section className="hero"><div className="hero-grid"/><div className="hero-orbit orbit-one"/><div className="hero-orbit orbit-two"/><div className="hero-ghost">BBC</div><div className="hero-copy"><div className="eyebrow"><span className="tiny-dot"/> YOUR ON-CHAIN +1</div><h1>A little chaotic.<br/>A lot <span>on-chain.</span></h1><p>The waifu who watches the chain<br className="desktop"/> so you don’t have to.</p><div className="hero-actions"><a className="button primary" href="#scanner">Meet your companion <ArrowUpRight size={18}/></a><a className="text-link" href="#intelligence">Explore her intelligence <ArrowRight size={17}/></a></div><div className="hero-caption"><span>BIG BOOTY CLANK</span><i/> Behavioral Blockchain Companion</div></div><div className="character-wrap"><img className="character" src="/bbc-character.png" alt="BBC, the purple-clad anime blockchain companion" fetchPriority="high"/><div className="character-fade"/></div><div className="float-card mood-card"><div className="micro">BBC MOOD SYSTEM <span>DEMO</span></div><div className="mood-title" style={{color:moods[mood].color}}><span className="tiny-dot"/>{moods[mood].name}</div><p key={mood}>{moods[mood].line}</p><div className="waveform">{Array.from({length:25},(_,i)=><i key={i} style={{height:8+(i*13%24),animationDelay:`${i*.09}s`}}/>)}</div></div><div className="float-card signal-card"><ScanLine size={20}/><div><strong>Eyes on the chain.</strong><span>Always curious. Never asleep.</span></div><span className="signal-cross">+</span></div><div className="hero-bottom"><span>INTELLIGENCE WITH PERSONALITY.</span><a href="#intelligence">SCROLL TO DISCOVER <ChevronDown size={15}/></a><span>01 / THE COMPANION</span></div></section>
 <div className="ticker"><span>ON-CHAIN INTELLIGENCE</span><b>✳</b><span>OFF-CHAIN ATTITUDE</span><b>✳</b><span>POWERED BY CURIOSITY</span><b>✳</b><span>BUILT FOR THE CLANK ERA</span><b>✳</b></div>
 <section id="intelligence" className="section reveal"><div className="section-top"><div><div className="eyebrow">01 / HER TOOLKIT</div><h2>Beauty. Brains.<br/><span>Blockchain.</span></h2></div><p>A whole intelligence stack.<br/>One very opinionated companion.</p></div><div className="module-grid"><a className="module featured" href="#scanner"><div className="module-top"><ScanLine/><span>ANALYZE</span><ArrowUpRight/></div><h3>BBC Scanner</h3><p>Drop a contract. Get the context.<br/>She’ll read between the transactions.</p><div className="scanner-visual"><div className="scan-line"/>{[35,65,42,83,55,95,72,48,83,62,92,68,80,51,98,72,48,80].map((h,i)=><i key={i} style={{height:h+'%'}}/>)}</div><span className="module-bottom">TRY THE INTERACTIVE DEMO <ArrowRight size={16}/></span></a>{modules.map((m,i)=><article className={'module '+(expanded===i?'expanded':'')} key={m.name}><div className="module-top"><m.icon/><span>{m.tag}</span><span className="module-number">0{i+2}</span></div><h3>{m.name}</h3><p>{m.text}</p><button className="module-bottom" aria-expanded={expanded===i} onClick={()=>setExpanded(expanded===i?null:i)}>{expanded===i?'LESS DETAIL':'EXPLORE MODULE'}<span>{expanded===i?'−':'+'}</span></button>{expanded===i&&<div className="module-detail">{m.detail}{i===3&&<div className="memory-list">{history.length?history.map(a=><button key={a} onClick={()=>{setAddress(a);document.getElementById('scanner')?.scrollIntoView({behavior:'smooth'})}}>{a.slice(0,10)}…{a.slice(-6)} ↗</button>):'No demo scans saved yet.'}</div>}</div>}</article>)}</div></section>
 <section id="scanner" className="section scanner-section reveal"><div className="scanner-intro"><div className="eyebrow">02 / TRUST THE RECEIPTS</div><h2>Go on.<br/><span>Give her a lead.</span></h2><p>No complicated dashboards.<br/>Just a contract address and a little curiosity.</p><div className="bbc-quote"><img src="/bbc-character.png" alt=""/><p>“Cute ticker. But what’s the<br/>deployer been up to?”<span>— BBC, probably</span></p></div></div><div className="scanner-panel"><div className="panel-heading"><span><ScanLine size={18}/> BBC Scanner</span><span className="badge">INTERACTIVE DEMO</span></div><label htmlFor="contract">Token / contract address</label><form onSubmit={e=>{e.preventDefault();scan()}}><div className="input-wrap"><input id="contract" value={address} onChange={e=>{setAddress(e.target.value);setError('');setResult(false)}} placeholder="0x… paste an EVM contract" disabled={scanning} autoComplete="off" spellCheck={false}/><button className="button primary" disabled={scanning}>{scanning?'Scanning…':'Scan'}<ArrowUpRight size={17}/></button></div></form>{error&&<p className="error" role="alert">{error}</p>}<button className="sample-link" onClick={()=>{setAddress(sample);setResult(false);setError('')}} disabled={scanning}>Just exploring? Load a sample contract ↗</button><div className={'scan-output '+(scanning?'scanning':'')} aria-live="polite">{scanning?<><div className="loader"/><h3>Following the breadcrumbs…</h3><p>Reading the demo liquidity and holder profile.</p></>:result?<><div className="result-title"><span>DEMO ANALYSIS</span><span>Sample dataset · not live</span></div><h3>“Interesting. But let’s look closer.”</h3><div className="metrics"><div><span>Liquidity</span><b>$284.6K</b></div><div><span>Holders</span><b>1,842</b></div><div><span>Top 10 share</span><b className="amber">38.2%</b></div></div><p>The sample shows active trading, but concentrated holdings deserve a closer look. These illustrative metrics are the same for every address.</p><div className="result-note"><Shield size={15}/> Token metrics, not an investment rating.</div></>:<><div className="scan-icon"><ScanLine size={28}/></div><h3>Every contract tells a story.</h3><p>Let’s see what yours is hiding.</p><div className="scan-tags"><span>Liquidity</span><span>Holders</span><span>Deployer</span><span>Momentum</span></div></>}</div><div className="panel-footer"><span><Shield size={14}/> No wallet connection needed</span><span>READ-ONLY</span></div></div></section>
 <section className="personality section reveal"><div className="eyebrow">03 / MORE THAN A DASHBOARD</div><h2>Data is cold.<br/>Your companion <em>isn’t.</em></h2><p>Playful by nature. Analytical by design.<br/>BBC turns wallet movements and market behavior into context you can actually follow.</p><div className="mood-controls" aria-label="Preview BBC moods">{moods.map((m,i)=><button key={m.name} onClick={()=>setMood(i)} aria-pressed={mood===i} className={mood===i?'active':''}>{m.name}</button>)}</div><div className="mood-speech" aria-live="polite">“{moods[mood].line}”</div><span className="micro muted">MOOD PREVIEW · CYCLES AUTOMATICALLY · LIVE DATA CONNECTION COMING SOON</span></section>
 <section id="architecture" className="section architecture reveal"><div className="section-top"><div><div className="eyebrow">04 / UNDER THE PERSONALITY</div><h2>Serious tech.<br/><span>Unserious energy.</span></h2></div><p>Designed to turn on-chain signals<br/>into a companion that understands context.</p></div><div className="architecture-flow">{[{icon:Network,title:'Observe',tag:'01 / ON-CHAIN SIGNALS',text:'Token activity · Wallets · Liquidity'},{icon:Database,title:'Understand',tag:'02 / BEHAVIORAL ENGINE',text:'Patterns · Context · Memory'},{icon:Brain,title:'Connect',tag:'03 / COMPANION LAYER',text:'Conversation · Mood · Insights'}].map((s,i)=><div className="architecture-step" key={s.title}><div className="arch-icon"><s.icon size={27}/></div><span className="micro">{s.tag}</span><h3>{s.title}</h3><p>{s.text}</p>{i<2&&<ArrowRight className="flow-arrow"/>}</div>)}</div><div className="architecture-note"><Zap size={15}/><span>THE BLUEPRINT FOR BBC · INTELLIGENCE ENGINE IN DEVELOPMENT</span></div></section>
 <section id="terminal" className="section terminal-section reveal"><div className="terminal"><div className="terminal-bar"><div className="terminal-dots"><i/><i/><i/></div><span>bbc@clank: ~/companion</span><button aria-label="Replay terminal sequence" onClick={()=>setLines(1)}>↻ REPLAY</button></div><div className="terminal-body">{terminalLines.slice(0,lines).map((line,i)=><div key={i} className={i===terminalLines.length-1?'terminal-final':i>0&&i<4?'terminal-success':''}>{line}</div>)}{lines<terminalLines.length&&<span className="cursor">▌</span>}</div></div><div className="launch-caption"><span>She’s getting ready. You should be too.</span><a href="#scanner">Explore the demo <ArrowUpRight size={17}/></a></div></section>
 <footer><a className="brand" href="#"><span className="brand-symbol">b.</span>BBC</a><p>Big Booty Clank. Bigger on-chain energy.</p><span>© {new Date().getFullYear()} BBC</span><a href="#">BACK TO TOP ↑</a></footer>
 </main>
}
